
version: 2

sources:
  - name: women_empowerment
    database: women-empowerment-490409
    schema: source
    tables:
      - name: whr_2015
        description: "Tabella World Happiness Report 2015"
        columns:
          - name: Country
          - name: Region
          - name: Happiness Rank
          - name: Happiness Score
          - name: Standard Error
          - name: Economy _GDP per Capita_
          - name: Family
          - name: Health _Life Expectancy_
          - name: Freedom
          - name: Trust _Government Corruption_
          - name: Generosity
          - name: Dystopia Residual
      - name: whr_2016
        description: "Tabella World Happiness Report 2016"
        columns:
          - name: Country
          - name: Region
          - name: Happiness Rank
          - name: Happiness Score
          - name: Lower Confidence Interval
          - name: Upper Confidence Interval
          - name: Economy _GDP per Capita_
          - name: Family
          - name: Health _Life Expectancy_
          - name: Freedom
          - name: Trust _Government Corruption_
          - name: Generosity
          - name: Dystopia Residual
      - name: whr_2017
        description: "Tabella World Happiness Report 2017"
        columns:
          - name: Country
          - name: Happiness_Rank
          - name: Happiness_Score
          - name: Whisker_high
          - name: Whisker_low
          - name: Economy__GDP_per_Capita_
          - name: Family
          - name: Health__Life_Expectancy_
          - name: Freedom
          - name: Generosity
          - name: Trust__Government_Corruption_
          - name: Dystopia_Residual
      - name: whr_2018
        columns:
          - name: Overall rank
          - name: Country or region
          - name: Score
          - name: GDP per capita
          - name: Social support
          - name: Healthy life expectancy
          - name: Freedom to make life choices
          - name: Generosity
          - name: Perceptions of corruption
      - name: whr_2019
        description: "Tabella World Happiness Report 2019"
        columns:
          - name: Overall rank
          - name: Country or region
          - name: Score
          - name: GDP per capita
          - name: Social support
          - name: Healthy life expectancy
          - name: Freedom to make life choices
          - name: Generosity
          - name: Perceptions of corruption
      - name: whr_2020
        description: "Tabella World Happiness Report 2020"
        columns:
          - name: Country name
          - name: Regional indicator
          - name: Ladder score
          - name: Standard error of ladder score
          - name: upperwhisker
          - name: lowerwhisker
          - name: Logged GDP per capita
          - name: Social support
          - name: Healthy life expectancy
          - name: Freedom to make life choices
          - name: Generosity
          - name: Perceptions of corruption
          - name: Ladder score in Dystopia
          - name: Dystopia + residual 
      - name: whr_2021
        description: "Tabella World Happiness Report 2021"
        columns:
          - name: Country name
          - name: Regional indicator
          - name: Ladder score
          - name: Standard error of ladder score
          - name: upperwhisker
          - name: lowerwhisker
          - name: Logged GDP per capita
          - name: Social support
          - name: Healthy life expectancy
          - name: Freedom to make life choices
          - name: Generosity
          - name: Perceptions of corruption
          - name: Ladder score in Dystopia
          - name: Dystopia + residual
      - name: whr_2022
        description: "Tabella World Happiness Report 2022"
        columns:
          - name: RANK
          - name: Country
          - name: Happiness score
          - name: Whisker-high
          - name: Whisker-low
          - name: Dystopia _1_83_ + residual
          - name: Explained by:GDP per capita
          - name: Explained by:Social support
          - name: Explained by:Healthy life expectancy
          - name: Explained by:Freedom to make life choices
          - name: Explained by:Generosity
          - name: Explained by:Perceptions of corruption
      - name: women_empowerment_index
        description: "Dati sull'empowerment femminile e parità di genere 2021-2022"
        columns:
          - name: Country
          - name: Women's Empowerment Index _WEI_ - 2022
          - name: Women's Empowerment Group - 2022
          - name: Global Gender Parity Index _GGPI_ - 2022
          - name: Gender Parity Group - 2022
          - name: Human Development Group - 2021
          - name: Sustainable Development Goal regions
      - name: gii_years
        description: "Indice di Disuguaglianza di Genere (serie storica)"
        columns:
          - name: countryIsoCode
          - name: country
          - name: indexCode
          - name: index
          - name: dimension
          - name: indicatorCode
          - name: indicator
          - name: year
          - name: actualValue
          - name: value
      - name: indicators_education
        description: "Tabella degli indicatori sull'istruzione per paese e genere (2015-2022)."
        columns:
          - name: year
            description: "L'anno di riferimento dei dati."
          - name: time_code
            description: "Codice temporale del periodo."
          - name: country_name
            description: "Nome completo del paese o della regione."
          - name: country_code
            description: "Codice ISO a 3 cifre del paese."
      # Bachelor's Degrees
          - name: Bachelors_f
            description: "Percentuale popolazione femminile (25+) con laurea triennale."
          - name: Bachelors_m
            description: "Percentuale popolazione maschile (25+) con laurea triennale."
          - name: Bachelors_tot
            description: "Percentuale totale popolazione (25+) con laurea triennale."
      # Lower Secondary
          - name: lower_secondary_f
          - name: lower_secondary_m
          - name: lower_secondary_tot
      # Post Secondary
          - name: post_secondary_f
          - name: post_secondary_m
          - name: post_secondary_tot
      # Primary
          - name: primary_f
          - name: primary_m
          - name: primary_tot
      # Short Cycle Tertiary
          - name: short_cycle_tertiary_f
          - name: short_cycle_tertiary_m
          - name: short_cycle_tertiary_tot
      # Upper Secondary
          - name: upper_secondary_f
          - name: upper_secondary_m
          - name: upper_secondary_tot
      # Master's Degrees
          - name: Masters_f
          - name: Master_m
          - name: Master_tot
      # Doctoral Degrees
          - name: Doctoral_f
          - name: Doctoral_m
          - name: Doctoral_tot