version: 2

sources:
  - name: women_empowerment
    database: women-empowerment-490409
    schema: source
    description: "Raw data loaded into BigQuery for women empowerment project"
    tables:
      - name: literacy_rate
        description: "Adult literacy rate total % of people ages 15 and above - World Bank"
      - name: whr_2015
        description: "World Happiness Report 2015"
      - name: whr_2016
        description: "World Happiness Report 2016"
      - name: whr_2017
        description: "World Happiness Report 2017"
      - name: whr_2018
        description: "World Happiness Report 2018"
      - name: whr_2019
        description: "World Happiness Report 2019"
      - name: whr_2020
        description: "World Happiness Report 2020"
      - name: whr_2021
        description: "World Happiness Report 2021"
      - name: whr_2022
        description: "World Happiness Report 2022"
      - name: gii_years
        description: "Gender Inequality Index across years"
      - name: women_empowerment_index
        description: "Women Empowerment Index 2022"
      - name: gdp
        description: "GDP dataset across years"